language: ruby
rvm:
  - 2.2.5
script: bundle exec rake -t
cache: bundler
services: mysql
before_install:
  - mysql -e "CREATE DATABASE IF NOT EXISTS HomeLibraryManager_test;"
  - bundle install --jobs=3 --retry=3
  - rake setup_travis